name: Frontend Code Coverage

on:
    pull_request:
        types: [opened, synchronize]

jobs:
  test-and-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Install dependencies
        working-directory: urban-cart-frontend
        run: npm install

      - name: Lint code
        working-directory: urban-cart-frontend
        run: npm run lint

      - name: Run tests with coverage
        working-directory: urban-cart-frontend
        run: npm run test:coverage